# Generated by Django 4.2.30 on 2026-06-15 06:44

from django.db import migrations, models
import ginasio_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('ginasio_app', '0002_descricao_blank'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome de quem vai usar a chave', max_length=100)),
                ('key', models.CharField(default=ginasio_app.models.generate_api_key, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expiration_date', models.DateTimeField(help_text='Data e hora de expiração da chave')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
            },
        ),
    ]
