# Generated by Django 4.2.30 on 2026-04-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenciatura',
            name='razoes_escolha',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unidadecurricular',
            name='bibliografia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unidadecurricular',
            name='conteudos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unidadecurricular',
            name='metodologia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unidadecurricular',
            name='objetivos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
