# Generated by Django 4.2.30 on 2026-04-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_licenciatura_razoes_escolha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadecurricular',
            name='avaliacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unidadecurricular',
            name='natureza',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
