# Generated by Django 4.2.30 on 2026-04-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_unidadecurricular_avaliacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencia',
            name='nivel',
            field=models.IntegerField(choices=[(1, 'Básico'), (2, 'Intermédio'), (3, 'Avançado'), (4, 'Especialista')], default=1),
        ),
        migrations.AddField(
            model_name='projeto',
            name='url_deploy',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tfc',
            name='link_repositorio',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='repositorio_git',
            field=models.URLField(blank=True, null=True),
        ),
    ]
