# Generated by Django 4.2.30 on 2026-04-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_competencia_nivel_projeto_url_deploy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makingof',
            name='imagem_caderno',
            field=models.ImageField(blank=True, null=True, upload_to='makingof/'),
        ),
    ]
