# Generated by Django 4.2.30 on 2026-05-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_makingof_imagem_caderno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videotutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('youtube_id', models.CharField(help_text='ID do vídeo no YouTube (ex: dQw4w9WgXcQ)', max_length=50)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'videotutorial',
                'verbose_name_plural': 'videotutoriais',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
