# Generated by Django 4.2.30 on 2026-05-18 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artigos', '0003_fix_authors_group_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='nome_autor',
            field=models.CharField(blank=True, help_text='Para utilizadores não autenticados', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_artigos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='artigos.artigo')),
                ('utilizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings_artigos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(condition=models.Q(('utilizador__isnull', False)), fields=('artigo', 'utilizador'), name='unique_rating_artigo_utilizador'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(condition=models.Q(('session_key__isnull', False)), fields=('artigo', 'session_key'), name='unique_rating_artigo_session'),
        ),
    ]
